### ISSUE TITLE
Query about metrics computation

### ISSUE THREAD

**Issue by aksh555** [siat-nlp/DDMN#2]
```
def update(self, metrics_list):
    for i, metrics in enumerate(metrics_list):
        num_samples = metrics.pop("num_samples", 1)
        self.num_samples += num_samples
        for key, val in metrics.items():
            if val is not None:
                key_turn = str(key) + "-turn-{}".format(str(i+1))
                self.metrics_val[key_turn] = val

                if isinstance(val, torch.Tensor):
                    val = val.item()
                    self.metrics_cum[key] += val * num_samples
                elif isinstance(val, tuple):
                    assert len(val) == 2
                    val, num_words = val[0].item(), val[1]
                    self.metrics_cum[key] += np.array([val * num_samples, num_words])
                else:
                    self.metrics_cum[key] += val * num_samples
```

Wanted to know the reason for scaling the metrics with the number of samples in the batch, and how can one compute the perplexity for the test set

**Comment by iwangjian** [comment]
Hi, `one batch` here denotes `one batch of dialogs`, not `one batch of samples`. In multi-turn dialogs, each dialog generally consists of multiple <user, bot> pairs (i.e., multiple samples). Therefore, here we aim to show the metrics of each turn, i.e., of each sample. Besides, the computations of different metrics are defined in `metrics.py`, you can define how to compute the perplexity there.
